---
abstract: 'A Generic Assertion checking class'
author:
  - 'Kent Fredric <kentnl@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: '0'
  File::Spec: '0'
  Test::Fatal: '0'
  Test::More: '0'
  Test::Warnings: '0'
  perl: '5.006'
configure_requires:
  ExtUtils::MakeMaker: '0'
  perl: '5.006'
dynamic_config: 0
generated_by: 'Dist::Zilla version 6.008, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Generic-Assertions
provides:
  Generic::Assertions:
    file: lib/Generic/Assertions.pm
    version: '0.001003'
requires:
  Carp: '0'
  perl: '5.006'
  strict: '0'
  warnings: '0'
resources:
  bugtracker: https://github.com/kentnl/Generic-Assertions/issues
  homepage: https://github.com/kentnl/Generic-Assertions
  repository: https://github.com/kentnl/Generic-Assertions.git
version: '0.001003'
